version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.2.4

    steps:
      - checkout
      - run:
          name: Install PHP Dependencies
          command: composer install

      - run:
          name: Run PHPUnit Tests
          command: |
            if [ "$RUN_TESTS" = "true" ]; then
              ./vendor/bin/phpunit
            else
              echo "Skipping tests."
            fi

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          environment:
            RUN_TESTS: false
