version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/php:8.2.4

    steps:
      - checkout
      - run:
          name: Install PHP Dependencies
          command: composer install

      - run:
          name: Run Admin PHPUnit Tests
          command: |
            ./vendor/bin/phpunit tests/admin

      - run:
          name: Run Users PHPUnit Tests
          command: |
            ./vendor/bin/phpunit tests/users

workflows:
  version: 2
  my-workflow:
    jobs:
      - build_and_test
