version: 2.1

jobs:
  run_phpunit_tests:
    docker:
      - image: php:8.2.4

    steps:
      #- restore_cache:
       #   keys:
        #    - v1-dependencies-{{ checksum "composer.lock" }}
         #   - v1-dependencies-
      - checkout
      - run:
          name: Check Composer Version
          command: composer --version

      - run:
          name: Install PHP Dependencies
          command: composer install

      - run:
          name: Run Admin PHPUnit Tests
          command: |
            ./vendor/bin/phpunit tests/admin

      - run:
          name: Run Users PHPUnit Tests
          command: |
            ./vendor/bin/phpunit tests/users
      #- save_cache:
       #   paths:
        #    - vendor
         # key: v1-dependencies-{{ checksum "composer.lock" }}

  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/vps:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/vps:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_phpunit_tests:
          filters:
            branches:
              only: master
      - build_and_push_docker_image:
          requires:
            - run_phpunit_tests
          filters:
            branches:
              only: master
