version: 2.1

jobs:
  run_phpunit_tests:
    docker:
      - image: php:8.2.4

    steps:
      - checkout

      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('sha384', 'composer-setup.php') === '795f976fe0ebd8b75f26a6dd68f78fd3453ce79f32ecb33e7fd087d39bfeb978342fb73a72f50b7c48e02867fd9363e') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            php -r "unlink('composer-setup.php');"

      - run:
          name: Check Composer Version
          command: /usr/local/bin/composer --version

      - run:
          name: Install PHP Dependencies
          command: composer install

      - run:
          name: Run Admin PHPUnit Tests
          command: |
            ./vendor/bin/phpunit tests/admin

      - run:
          name: Run Users PHPUnit Tests
          command: |
            ./vendor/bin/phpunit tests/users

  build_and_push_docker_image:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/vps:${CIRCLE_SHA1} .

      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/vps:${CIRCLE_SHA1}

      - run:
          name: Check PATH
          command: echo $PATH

      - run:
          name: Set PATH
          command: export PATH=$PATH:/usr/local/bin

      - run:
          name: Check PHP Version
          command: php --version

      - run:
          name: Check Composer Version
          command: /usr/local/bin/composer --version

      - run:
          name: List /usr/local/bin
          command: ls -l /usr/local/bin

      - run:
          name: Debug Shell
          command: /bin/bash

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - run_phpunit_tests:
          filters:
            branches:
              only: master

      - build_and_push_docker_image:
          requires:
            - run_phpunit_tests
          filters:
            branches:
              only: master
