version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: vpmsdb


  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: vpmsdb
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
